name: CI

on: [push, pull_request]

jobs:
  build-gnu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake git g++

    - name: Compile with g++
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=on -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
        make

    - name: Run tests
      run: |
        cd build
        ./TestSyriusUtils

  build-clang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake git clang

      - name: Compile with clang
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=on -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          make

      - name: Run tests
        run: |
          cd build
          ./TestSyriusUtils

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: choco install cmake git

    - name: Compile with MSVC
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=on
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ./Release/TestSyriusUtils.exe
