name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ${{ matrix.compiler }}
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: ${{ matrix.compiler }}

    - name: Compile with ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_C_COMPILER=${{ matrix.compiler }}
        make

    - name: Run tests
      run: |
        cd build
        ctest
